### PR TITLE
Support for multi-frame DICOMs and 16-bit signed integer with RescaleSlope/Intercept.

### PR DESCRIPTION
**Pull request by Sethur**
Added full support for multi-frame DICOMs, especially when using 16bit signed integer as data type and working with RescaleIntercept and RescaleSlope.

### CODE REVIEW

**Comment by rasband** [comment]
Please provide an example of a 16-bit signed multi-frame DICOM that does not open correctly in ImageJ.

**Comment by Sethur** [comment]
@rasband When I tested my patch, I used official example multi-frame DICOM files provided by NEMA ftp://medical.nema.org/medical/dicom/Multiframe/CT/nemamfct.images.tar.bz2

The archive contains signed and unsigned multi-frame DICOM images in a numbered format. I did not test the patch with all of them, but I remember that especially numbers 2 and 50 did not work properly. The patch should allow 16 bit signed single and multi-frame DICOMs to work with and without the "convertToFloat" option. It should also honor the "ignoreRescaleSlope" setting for all cases.

**Comment by Sethur** [comment]
@rasband 
Unfortunately, the archive of multi-frame DICOMs above does not contain examples with RescaleSlope != 1.0. The handling for the 16bit signed DICOMs was still wrong, but for different reasons (which are also fixed with this patch).

To make things easier, I modified two of the DICOMs in the archive above (one with data encoding 16bit signed and one with 16bit unsigned) to have RescaleIntercept = -2048 and RescaleSlope = 2.0

Both of them are not handles correctly with ImageJ v1.52r. When handles correctly, air should be at around -2000 HU.

[Multiframe_Examples.zip](https://github.com/imagej/imagej1/files/3858194/Multiframe_Examples.zip)

**Comment by rasband** [comment]
This version of the the DICOM reader opens a PT series with differing Rescale Slope values  as a 16-bit stack. Isn't it necessary to open such as series as 32-bit so the Rescale Slope can be applied separately to each image in the series? Here is an example:
[PET Series.zip](https://github.com/imagej/imagej1/files/3865369/PET.Series.zip)

**Comment by Sethur** [comment]
@rasband
This is a valid point, I did not consider the fact that the RescaleSlope could change from DICOM file to DICOM file when importing a continuous volume.

However, considering this, the RescaleIntercept might change from slice to slice just as well (although in your example, it's always 0.0). Since the DICOM Reader has no way of knowing whether the RescaleIntercept _and_ RecaleSlope will be the same for all files that belong to the imported series, wouldn't we always need to convert to 32-bit? 

I'm not sure what would happen if only a few slices of an incoming series are converted to 32-bit but the rest are left at 16-bit. I'll commit an update to the pull request after having a look at the code tomorrow.

**Comment by Sethur** [comment]
@rasband
After examining this further, I concluded that:

- There might be DICOM series (consisting of several files) that define both different RescaleIntercepts and RescaleSlopes for every slice/file. However, this is a rare scenario, especially in the case of different RescaleIntercept values.

- The problem with the current solution (before this patch) is, that it will convert to 32-bit even if the RescaleSlope is the same, but not 1.0, on every slice (happens quite frequently).

- From what I know, ImageJ only supports calibrations for the whole stack, not for individual slices. So the only way of getting everything right for all DICOM series is to convert to 32-bit every time, which comes with a performance penalty and obfuscates the original data type.

- A possible solution apart from converting all DICOMs to 32-bit by default is to add another Option under `Options->DICOM` saying `Support series with varying slope and intersect` which effectively triggers the conversion to 32-bit. This could even be off by default

- Another solution would be to implement per-slice-calibration, but this would probably interfere with existing code too much.

What would be your preferred way of handling this? 

As a start, I just committed an update to the patch that triggers `openAsFloat` again in case of `RescaleSlope != 0`, so that at least the behavior should be as before when it cames to varying RescaleSlopes. That way you could merge this patch without breaking existing functionality.

**Comment by rasband** [comment]
The fix for the bug that caused Rescale Slope/Intercept to not be applied with multi-frame DICOMs is in the latest daily build (1.52s57). The other changes are omitted because they caused failures in a test script I ran on the 50 DICOMs I have collected over the past 20 years. Code changes are at
https://github.com/imagej/imagej1/commit/d2c729a690039cf292c869709011b4941ec78e78

**Comment by Sethur** [comment]
@rasband
I guess this will not fix the issue with 16bit signed DICOMs (single or multiframe) that have RescaleSlope = 1 but RescaleIntercept != 0 as they will not automatically be converted to float and have a preexisting calibration.
Would you be willing to share the conflicting DICOMs? Then I could adapt the fix accordingly.

**Comment by rasband** [comment]
Today's daily build (1.52s58) fixes the issue with 16bit signed DICOMs that have RescaleSlope = 1 but RescaleIntercept != 1. Code changes are at
https://github.com/imagej/imagej1/commit/962a21c9afa1d67263bd2d6b3b663ba3979c3321

**Pull request closed without merging**
