### PR TITLE
Mayday

### PR DESCRIPTION
**Pull request by dprodanov**
Test generic parametrization of Overlay.java

### CODE REVIEW

**Comment by ctrueden** [comment]
@rasband I fixed the conflicts and whitespace errors, so the "Files changed" tab shows a much cleaner patch now.

@dprodanov Could you please comment on your intent here? Just tightening up the typing?

@rasband If you are OK with parameterizing types in this way, it could be done in many more places... what do you think?

**Comment by rasband** [comment]
I do not see the need to parameterize types in this way.

**Comment by dprodanov** [comment]
Hi Wayne,

Type parametrization is already accepted practice in Java for more than 10
years.
Why do you insist on the legacy coding practices?

best regards,

Dimiter

**Comment by rasband** [comment]
These changes are in the latest daily build (1.53b21).

**Pull request closed without merging**
